### ISSUE TITLE
error message from wilcoxon test when CI is chosen

### ISSUE THREAD

**Issue by haz060** [nlp-stat-test/nlp-stat-test#67]
Traceback (most recent call last):
  File "run-gui.py", line 904, in sigtest
    resp.set_cookie('wilcoxon_ci_rec', wilcoxon_ci_rec)
  File "/Users/haotianzhu/anaconda3/envs/nlp-stat-test/lib/python3.8/site-packages/werkzeug/wrappers/base_response.py", line 468, in set_cookie
    dump_cookie(
  File "/Users/haotianzhu/anaconda3/envs/nlp-stat-test/lib/python3.8/site-packages/werkzeug/http.py", line 1219, in dump_cookie
    buf = [key + b"=" + _cookie_quote(value)]
  File "/Users/haotianzhu/anaconda3/envs/nlp-stat-test/lib/python3.8/site-packages/werkzeug/_internal.py", line 268, in _cookie_quote
    for char in iter_bytes(b):
TypeError: 'NoneType' object is not iterable

**Comment by DeniseMak** [comment]
Fixed by https://github.com/nlp-stat-test/nlp-stat-test/commit/94d7203b3a762914e96097135d02995c14494571
